DojoReads/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app1.urls')),
]

app1/urls.py
from django.contrib import admin
from django.urls import path
from . import views 

app_name = 'app1'

urlpatterns = [
    path('', views.registration, name='registration'),
    path('register', views.register, name='register'),
    path('login', views.login, name='login'),
    path('logout', views.logout, name='logout'),
    path('books', views.books_home, name='books_home'),
    path('books/add', views.books_add, name='books_add'),
    path('books/add_new', views.add_new_book, name='add_new_book'),
    path('books/<int:pk>', views.books_num, name='books_num'),
    path('users/<int:pk>', views.users_num, name='users_num'),
    path('add_review', views.add_review, name='add_review'),
    path('delete_review/<int:pk>', views.delete_review,  name='delete_review'),
]

app1/models.py
from django.db import models



class Authors(models.Model):
    name = models.CharField(max_length=125)
    
    def __str__(self) -> str:
        return self.name


#this for validation
class BooksManger(models.Manager):
    def validate(self, post_data):
        errors = {}
        if len(post_data['description']) < 5:
            errors['description'] = 'Description should be at least 5 charters'
        return errors
    
class Books(models.Model):
    author = models.ForeignKey(Authors, on_delete=models.CASCADE)
    title= models.CharField(max_length=255)
    created_at = models.DateTimeField(auto_now=True)
    updated_at = models.DateTimeField(auto_now_add=True)
    
    objects = BooksManger()
    
    def __str__(self):
        return str(self.title)




#this for validation
class UsersManger(models.Manager):
    def validate(self, post_data):
        errors = {}
        if len(post_data['first_name']) < 2:
            errors['first_name'] = 'First name should be at least 2 charters'
        if len(post_data['last_name']) < 2:
            errors['last_name'] = 'Last name should be at least 2 charters'    
        if len(post_data['password1']) < 8:
            errors['password1'] = 'Password should be at least 8 charters'
        return errors


class Users(models.Model):
    first_name = models.CharField(max_length=255)
    last_name = models.CharField(max_length=255)
    email= models.EmailField(unique=True)
    password = models.CharField(max_length=128)
    created_at = models.DateTimeField(auto_now=True)
    updated_at = models.DateTimeField(auto_now_add=True)
    objects = UsersManger()


    def __str__(self):
        return str({self.first_name,self.last_name,self.email})

class Reviews(models.Model):
    user = models.ForeignKey(Users, on_delete=models.CASCADE)
    book = models.ForeignKey(Books, on_delete=models.CASCADE)
    review=models.TextField() 
    stars = models.IntegerField()
    created_at = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return str(self.book.title)
    
    def get_blank_stars_count(self):
        return 5 - self.stars

app1/views.py
from django.shortcuts import render,redirect
from .models import Users, Reviews, Authors, Books
from django.contrib import messages
import bcrypt

def registration(request):
    user_id = request.session.get('user_id')
    
    if user_id:
        return redirect('app1:books_home')
    
    return render(request, "registration.html") 


def register(request):
    if request.method == "POST":
        
        errors = Users.objects.validate(request.POST)
        
        # There is some errors
        if len(errors) > 0:
            for error in errors.values():
                messages.error(request, error)
            return redirect('app1:registration')
        
        first_name_form = request.POST['first_name']
        last_name_form = request.POST['last_name']
        email_form = request.POST['email']
        password_form = request.POST['password1']
        confirm_password_form = request.POST['password2']
        
        if password_form == confirm_password_form:
            hash_password = bcrypt.hashpw(password_form.encode(), bcrypt.gensalt()).decode()
            
            new_user =Users.objects.create(
                first_name=first_name_form,
                last_name = last_name_form,
                email=email_form,
                password=hash_password)
            
            
            request.session['user_id'] = new_user.id
            return redirect('app1:books_home')

        # if password didn't match
        else:
            messages.error(request, 'Password not match.')
            return redirect('app1:registration')



def login(request):
    if request.method == "POST":
        email_form = request.POST['email']
        password_form = request.POST['password1']
        
        users = Users.objects.filter(email=email_form)
        
        if len(users) == 0:
            messages.error(request, "Email doesn't exist.")
            return redirect('app1:registration')
        
        if bcrypt.checkpw(password_form.encode(), users.first().password.encode()):
            request.session['user_id'] = users.first().id
            return redirect('app1:books_home')
        # if password is wrong
        else:
            messages.error(request, 'Password not correct.')
            return redirect('app1:registration')



def logout(request):
    request.session.flush()
    return redirect('app1:registration')


def books_home(request):
    user_id = request.session.get('user_id')
    # if user not logged in
    if not user_id:
        return redirect('app1:registration')
    
    user = Users.objects.get(id=user_id)
    
    context={
        'user': user,
        'reviews': Reviews.objects.filter().order_by('-created_at')[:3],
        'books':  Books.objects.all()
    }
    return render(request, 'books_home.html', context)



# books_add
def books_add(request):
    all_authors = Authors.objects.all()
    context = {
        'authors' : all_authors
    }
    return render(request, "books_add.html", context)

def add_new_book(request):
    form_title = request.POST['title']
    # THE AUTHOR  ID SELECTED FROM THE FORM
    form_selected_author_id = request.POST.get('selected_author', None)
    form_new_author = request.POST.get('new_author', None)
    form_review = request.POST['review']
    form_stars = request.POST['stars']
    
    # IF USER ADDED NEW AUTHOR
    if form_new_author:
        # GET THE AUTHOR USING THE ID
        new_author = Authors.objects.create(name=form_new_author)
        book = Books.objects.create(title=form_title, author=new_author)
    # CHECK IF USER SELECTED EXISTING AUTHOR
    else:
        selected_author = Authors.objects.get(id = form_selected_author_id)
        book = Books.objects.create(title=form_title, author=selected_author)
        
    # TO CREATE NEW REVIEW WE SHOULD HAVE (BOOK - USER - REVIEW - STARS)
    
    # WE DON'T HAVE THE USER SO WE SHOULD GET IT 
    user_id = request.session.get('user_id')
    current_user = Users.objects.get(id=user_id)
    
    review = Reviews.objects.create(user=current_user, book=book, review=form_review, stars=int(form_stars))
    
    return redirect('app1:books_num', pk=book.id)




def books_num(request, pk):
    book = Books.objects.get(id=pk)
    reviews_for_book = Reviews.objects.filter(book=book)
    
    user_id = request.session.get('user_id')
    current_user = Users.objects.get(id=user_id)
    
    context = {
        'book': book,
        'reviews': reviews_for_book,
        'user' : current_user
    }
    return render(request,"books_num.html", context)


def add_review(request):
    form_book_id = request.POST['book']
    form_stars = request.POST['stars']
    form_review = request.POST['review']
    
    # TO CREATE NEW REVIEW WE SHOULD HAVE (BOOK - USER - REVIEW - STARS)

    
    book = Books.objects.get(id=form_book_id)
    # WE DON'T HAVE THE USER SO WE SHOULD GET IT 
    user_id = request.session.get('user_id')
    current_user = Users.objects.get(id=user_id)
    
    review = Reviews.objects.create(user=current_user, book=book, review=form_review, stars=int(form_stars))
    
    return redirect('app1:books_num', pk=book.id)
    
def delete_review(request, pk):
    review = Reviews.objects.get(id=pk)
    review.delete()
    return redirect('app1:books_home')


# POST users_num
def users_num(request,pk):
    user_view=Users.objects.get(id=pk)
    user_reviews=Reviews.objects.filter(user=user_view)
    context={
              'user':user_view,
              'reviews':user_reviews
    }

   
    return render(request,"users_num.html",context)

app1/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="{% static 'bootstrap.min.css' %}" />
    <link rel="stylesheet" href="../static/button.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css">


  </head>
   <body>
    <h1>Welcome!</h1>
    
  <div class="container text-left mt-6">
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'app1:books_home'%}">Welcome , {{user.first_name}} !</a>
                    </li>
                </ul>
                <ul style="list-style: none;" class="ms-auto d-flex gap-3 m-0">
                    
                                        <li class="nav-item ">
                                            <a style="text-decoration: underline;" class="nav-link active" aria-current="page"href="{% url 'app1:books_add'%}">Add Book and Review</a>
                                        </li>
                                        <li class="nav-item ">
                                            <a style="text-decoration: underline;" class=" nav-link active text-primary" aria-current="page"  href="{% url 'app1:logout' %}">Log out</a>
                                        </li>

                </ul>
           
          </div>
        </div>
      </nav>
      <hr>
    <div class="container">
        {% block content %}

        {% endblock content %}
    </div>



</div>
<script src="{% static 'bootstrap.bundle.min.js' %}"></script>
</body>
</html>

app1/templates/books_add.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title> Add Books  and a Review : </title>
    <link rel="stylesheet" href="{% static 'bootstrap.min.css' %}" />
    <link rel="stylesheet" href="../static/button.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css">




    <!-- navbar -->
</head>
<body>
 
<div class="container text-left mt-6">
 <nav class="navbar navbar-expand-lg bg-body-tertiary">
     <div class="container-fluid">
         <div class="collapse navbar-collapse" id="navbarSupportedContent">
             
             <ul style="list-style: none;" class="ms-auto d-flex gap-3 m-0">
                 
                                     <li class="nav-item ">
                                         <a style="text-decoration: underline;" class="nav-link active text-primary " aria-current="page"href="{% url 'app1:books_home'%}">Home </a>
                                     </li>
                                     <li class="nav-item ">
                                         <a style="text-decoration: underline;" class=" nav-link active text-primary" aria-current="page"  href="{% url 'app1:logout' %}">Log out</a>
                                     </li>

             </ul>
        
       </div>
     </div>
   </nav>
   <br>



    <!-- the body -->

    <h4 class="mb-5">Add a New Book Title and a review:</h4>
    <div class="ms-5">
  <form action="{% url 'app1:add_new_book' %}" method="POST">
          {% csrf_token %}

           <!-- Title Input > type :"text" -->
         <div class="d-flex align-items-center gap-2">
            <label for="first_name" class=" col-form-label"> Book Title : </label>
            <div style="flex: 1.4" class="col-sm-4">
              <input required type="text" name="title" class="form-control w-50 border-2 border-black ms-3" id="first_name">
            </div>
          </div>
          <h6>Author:</h6>
          
          <span class="col-sm-2 col-form-label ms-4"> Choose from the list :</span>
            <select class="form-select  w-50 border-2 border-black d-inline mb-4 ms-3"  aria-label="Default select example" name="selected_author">
            {% for author in authors %}
             <option value={{author.id}}>{{author.name}}</option>
            {% endfor %}
          </select>
          <br>

          <!-- Added new author Input > type :"text" -->
        <div class="d-flex align-items-center gap-2">
           <label for="first_name" class="col-sm-2 col-form-label ms-4"> Or add a new author : </label>
           <div style="flex: 1.4" class="col-sm-4">
             <input  type="text" name="new_author" class="form-control  w-50 border-2 border-black" id="first_name">
           </div>
         </div>

         <!-- Review Input > type :"textarea" -->
          <div class="form-group">
              <label for="exampleFormControlTextarea1">Review:</label>
              <textarea class="form-control  w-50 border-2 border-black ms-6 " name="review" id="exampleFormControlTextarea1" rows="3"></textarea>
            </div>

<br>
            <label for="rating">Rating:</label>
            <select class="form-select border-2 border-black" aria-label="Default select example" style="width: max-content;" name="stars">
                <option value="1">1 star</option>
                <option value="2">2 stars </option>
                <option value="3">3 stars</option>
                <option value="4">4 stars</option>
                <option value="5">5 stars</option>
               </select>
               <br>



            <div class="submit-btn d-flex justify-content-end">
                <button style="width: fit-content;
            box-shadow: 2px 3px 0px 1px rgba(0, 0, 0, 1)
            , 0 2px 10px 0 rgba(0, 0, 0, 0.12);
            border: 2px solid black;" type="submit" class="btn btn-outline-dark btn-shadow mt-3"> Add Book and Review</button>
            </div>
    </form>
  </div>
    

</div>
<script src="{% static 'bootstrap.bundle.min.js' %}"></script>
</body>
</html>

app1/templates/books_home.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Books Home </title>
    <link rel="stylesheet" href="{% static 'bootstrap.min.css' %}" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css">
    <link rel="stylesheet" href="../static/button.css">




    <!-- navbar -->
</head>
<body>
 
<div class="container text-left mt-6">

 <nav class="navbar navbar-expand-lg bg-body-tertiary">
     <div class="container-fluid">
         <div class="collapse navbar-collapse" id="navbarSupportedContent">
             <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                 <li class="nav-item">
                     <a class="nav-link active" aria-current="page" href="{% url 'app1:books_home'%}">Welcome , {{user.first_name}} !</a>
                 </li>
             </ul>
             <ul style="list-style: none;" class="ms-auto d-flex gap-3 m-0">
                 
                                     <li class="nav-item ">
                                         <a style="text-decoration: underline;" class="nav-link active text-primary" aria-current="page"href="{% url 'app1:books_add'%}">Add Book and Review</a>
                                     </li>
                                     <li class="nav-item ">
                                         <a style="text-decoration: underline;" class=" nav-link active text-primary" aria-current="page"  href="{% url 'app1:logout' %}">Log out</a>
                                     </li>

             </ul>
        
       </div>
     </div>
   </nav>
  
    <!-- the body -->
    <div class="row mt-5">
        <div class="col-6">


    <h3 >Recent Book Reviews: </h4>
        <div class="rece">
    {% for review in reviews %}
        <h5><a href="{% url 'app1:books_num' pk=review.book.id %}">{{review.book.title}}</a></h5>
        <!-- <p>Rating: {{review.book.stars}}</p> -->
        <p>Rating: 
            {% for i in "x"|ljust:review.stars %}
                <i class="fa-solid fa-star"></i>
            {% endfor %}
            
            {% for i in "x"|ljust:review.get_blank_stars_count %}
                <i class="fa-regular fa-star"></i>
            {% endfor %}
          </p>
        <br>
    {% endfor %}
</div>
</div>

<!-- right side  -->
<div class="col-6"> 
<h4>Other Books with Reviews :</h4>
<div class="scrol">
{% for book in books %}
    <p><a style="text-decoration: underline;" href="{% url 'app1:books_num' pk=book.id %}">{{book.title}}</a></p>
{% endfor %}
</div>


</div>
</div>
</div>
<script src="{% static 'bootstrap.bundle.min.js' %}"></script>
</body>
</html>

app1/templates/books_num.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title> Add Books  and a Review : </title>
    <link rel="stylesheet" href="{% static 'bootstrap.min.css' %}" />
    <link rel="stylesheet" href="../static/button.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css">




    <!-- navbar -->
</head>
<body>
 
<div class="container text-left mt-6">
 <nav class="navbar navbar-expand-lg bg-body-tertiary">
     <div class="container-fluid">
         <div class="collapse navbar-collapse" id="navbarSupportedContent">
             
             <ul style="list-style: none;" class="ms-auto d-flex gap-3 m-0">
                 
                                     <li class="nav-item ">
                                         <a style="text-decoration: underline;" class="nav-link active text-primary " aria-current="page"href="{% url 'app1:books_home'%}">Home </a>
                                     </li>
                                     <li class="nav-item ">
                                         <a style="text-decoration: underline;" class=" nav-link active text-primary" aria-current="page"  href="{% url 'app1:logout' %}">Log out</a>
                                     </li>

             </ul>
        
       </div>
     </div>
   </nav>
   <br>


    <!-- the body -->
    
    <h3 class="pt-3">{{book.title}}</h3>
    <h3>Author: {{book.author.name}}</h3>
    
   

    <div class="row mt-5">
        <div class="col-6  me-5">
    <h4>Reviews</h4>
    <hr>
    {% for r in reviews %}
    <p>Rating: 
        {% for i in "x"|ljust:r.stars %}
            <i class="fa-solid fa-star"></i>
        {% endfor %}
        
        {% for i in "x"|ljust:r.get_blank_stars_count %}
            <i class="fa-regular fa-star"></i>
        {% endfor %}
      </p>        <p><a href="{% url 'app1:users_num' pk=r.user.id %}">{{r.user.first_name}}</a>   says: {{r.review}}</p>
        <p>{{r.created_at}}</p>
        {% if user == r.user %}
            <a style="text-decoration: underline;" class="text-primary" href="{% url 'app1:delete_review' pk=r.id %}">Delete this Review</a>
        {% endif %}
        <hr>
    {% endfor %}
    </div>

<!--right side  -->
   <div class="col-4 ms-5">

<h4>Add a Review :</h4>
<form action="{% url 'app1:add_review' %}" method="POST">
    {% csrf_token %}

    <!-- Review Input > type :"textarea" -->
    <div class="form-group">
        <textarea class="form-control border-2 border-black" name="review" id="exampleFormControlTextarea1" rows="3"></textarea>
      </div>

<br>
    <input type="hidden" name="book" value="{{book.id}}">
    <h4>Rating: </h4>
    <select class="form-select border-2 border-black" aria-label="Default select example" style="width: max-content;" name="stars">
        <option value="1">1 star</option>
        <option value="2">2 stars </option>
        <option value="3">3 stars</option>
        <option value="4">4 stars</option>
        <option value="5">5 stars</option>
    </select>
        <br>



      <div class="submit-btn d-flex justify-content-end">
          <button style="width: fit-content;
      box-shadow: 2px 3px 0px 1px rgba(0, 0, 0, 1)
      , 0 2px 10px 0 rgba(0, 0, 0, 0.12);
      border: 2px solid black;" type="submit" class="btn btn-outline-dark btn-shadow mt-3"> Submit Review</button>
      </div>
</form>
</div>
</div>


















</div>
<script src="{% static 'bootstrap.bundle.min.js' %}"></script>
</body>
</html>

app1/templates/registration.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Login & Registration</title>
    <link rel="stylesheet" href="{% static 'bootstrap.min.css' %}" />
    <link rel="stylesheet" href="../static/button.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css">


  </head>
   <body>
    
  <div class="container text-left mt-6">

<h1 class="mt-5">Welcome!</h1>
      
      <div class="row mt-5">
        <div class="col-lg-6">
          <div class="one">
    

                <br>
      <form action="{% url 'app1:register' %}" method="POST" class="d-flex flex-column gap-3 ">
        {% csrf_token %}
         <!-- Name Input > type :"text" -->
         <div class="d-flex align-items-center gap-2">
          <label for="first_name" class="col-sm-2 col-form-label"> First name : </label>
          <div style="flex: 1.4" class="col-sm-4">
            <input required type="text" name="first_name" class="form-control" id="first_name">
          </div>
        </div>
         <!-- Name Input > type :"text" -->
         <div class="d-flex align-items-center gap-2">
          <label for="last_name" class="col-sm-2 col-form-label"> Last name : </label>
          <div style="flex: 1.4" class="col-sm-4">
            <input required type="text" name="last_name" class="form-control" id="last_name">
          </div>
        </div>
          <!-- email Input > type :type="email" -->
          <div class="d-flex align-items-center gap-2">
            <label for="inputEmail3" class="col-sm-2 col-form-label"> Email : </label>
            <div style="flex: 1.4" class="col-sm-4">
              <input required type="email" name="email" class="form-control" id="email">
            </div>
          </div>
          <!-- email  password Input > type :"password" -->
          <div class="d-flex align-items-center gap-2">
            <label for="password1" class="col-sm-2 col-form-label"> Password : </label>
            <div style="flex: 1.4" class="col-sm-4">
             <input required type="password" name="password1" class="form-control" id="password1">
            </div>
          </div>

          <!-- confirm email  password Input > type :"password" -->
          <div class="d-flex align-items-center gap-2">
            <label for="password2" class="col-sm-2 col-form-label">  Confirm Password : </label>
            <div style="flex: 1.4" class="col-sm-4">
             <input required type="password" name="password2" class="form-control" id="password2">
            </div>
          </div>
        <!-- {{registration_form}} -->
        <button style="width: fit-content;
          box-shadow: 2px 3px 0px 1px rgba(0, 0, 0, 1)
          , 0 2px 10px 0 rgba(0, 0, 0, 0.12);
          border: 2px solid black;"
        type="submit" class="btn btn-outline-dark mt-3"> Registr</button>
      </form>

        </div>
        </div>





        <div class="col-lg-6">
          <div class="two">
          <br>
          <form action="{% url 'app1:login' %}" method="POST" class="d-flex flex-column gap-3 ">
            {% csrf_token %}
             <!-- email Input > type :type="email" -->
          <div class="d-flex align-items-center gap-2">
            <label for="inputEmail3" class="col-sm-2 col-form-label"> Email : </label>
            <div style="flex: 1.4" class="col-sm-4">
              <input required type="email" name="email" class="form-control" id="email">
            </div>
          </div>
          <!-- email  password Input > type :"password" -->
          <div class="d-flex align-items-center gap-2">
            <label for="password1" class="col-sm-2 col-form-label"> Password : </label>
            <div style="flex: 1.4" class="col-sm-4">
             <input required type="password" name="password1" class="form-control" id="password1">
            </div>
          </div>
    
            <!-- {{login_form}} -->
            <button style="width: fit-content;
            box-shadow: 2px 3px 0px 1px rgba(0, 0, 0, 1)
            , 0 2px 10px 0 rgba(0, 0, 0, 0.12);
            border: 2px solid black;" type="submit" class="btn btn-outline-dark btn-shadow mt-3"> Login </button>
          </form>
        </div>
        </div>
      </div> 
  </div>
  {% if messages %}
  <ul class="messages">
    {% for message in messages %}
      <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
  </ul>
  {% endif %}
    <script src="{% static 'bootstrap.bundle.min.js' %}"></script>
  </body>
</html>

app1/templates/users_num.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title> User Reviews : </title>
    <link rel="stylesheet" href="{% static 'bootstrap.min.css' %}" />
    <link rel="stylesheet" href="../static/button.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css">





    <!-- navbar -->
</head>
<body>
 
<div class="container text-left mt-6">
 <nav class="navbar navbar-expand-lg bg-body-tertiary">
     <div class="container-fluid">
         <div class="collapse navbar-collapse" id="navbarSupportedContent">
             
             <ul style="list-style: none;" class="ms-auto d-flex gap-3 m-0">
                 
                                     <li class="nav-item ">
                                         <a style="text-decoration: underline;" class="nav-link active text-primary " aria-current="page"href="{% url 'app1:books_home'%}">Home </a>
                                     </li>
                                     <li class="nav-item ">
                                        <a style="text-decoration: underline;" class="nav-link active text-primary" aria-current="page"href="{% url 'app1:books_add'%}">Add Book and Review</a>
                                    </li>
                                     <li class="nav-item ">
                                         <a style="text-decoration: underline;" class=" nav-link active text-primary" aria-current="page"  href="{% url 'app1:logout' %}">Log out</a>
                                     </li>

             </ul>
        
       </div>
     </div>
   </nav>
   <br>
    <!-- the body -->
    <h4>User : {{user.first_name}} </h4>
    <h4>Name : {{user.first_name}} {{user.last_name}}</h4>
    <h4>Email : {{user.email}} </h4>
    <h4>Total Review : {{reviews.count}} </h4>
<br>
<br>
    <h4>Posted Reviews on The following books: </h4>
           <br>
           {% for review in reviews %}
               <p><a style="text-decoration: underline;" href="{% url 'app1:books_num' pk=review.book.id %}">{{review.book.title}} </a></p>
           {% endfor %}    

           













 </div>
 <script src="{% static 'bootstrap.bundle.min.js' %}"></script>
 </body>
 </html>